version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
