# Generated by Django 4.2.7 on 2023-11-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='media/products/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('slug', models.SlugField(default='slug', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='category.category')),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['id', 'slug'], name='product_pro_id_b9e5a0_idx'), models.Index(fields=['title'], name='product_pro_title_07e491_idx')],
            },
        ),
    ]
