# Generated by Django 4.2.7 on 2023-11-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='slug', unique=True)),
                ('image', models.ImageField(null=True, upload_to='media/category_images', verbose_name='Фото категории')),
            ],
        ),
    ]
